import { useEffect, useMemo, useState } from "react";
import { createUserWithEmailAndPassword, getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, getDoc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { initializeApp } from "firebase/app";
import { Archive, Boxes, LogOut, Mail, MapPinned, PackageCheck, Pencil, Plus, Save, ShieldCheck, Trash2, Users, X } from "lucide-react";
import { auth, db, firebaseConfig } from "../../lib/firebase";
import "./firebase-admin.css";

type Tab = "products" | "orders" | "shipping" | "messages" | "users";
type Row = Record<string, any> & { id: string };
const statuses = ["Nouvelle", "Confirmée", "En préparation", "Expédiée", "Livrée", "Annulée"];

function useRows(path: string, sorted = false) {
  const [rows, setRows] = useState<Row[]>([]);
  useEffect(() => onSnapshot(sorted ? query(collection(db, path), orderBy("createdAt", "desc")) : collection(db, path), snap => setRows(snap.docs.map(d => ({ id: d.id, ...d.data() })))), [path, sorted]);
  return rows;
}

export default function FirebaseAdmin() {
  const [user, setUser] = useState(auth.currentUser), [role, setRole] = useState(""), [loading, setLoading] = useState(true), [tab, setTab] = useState<Tab>("orders");
  useEffect(() => onAuthStateChanged(auth, async current => { setUser(current); setRole(current ? (await getDoc(doc(db, "users", current.uid))).data()?.role ?? "" : ""); setLoading(false); }), []);
  if (loading) return <div className="admin-loading">Chargement du back-office…</div>;
  if (!user) return <Login />;
  const employee = role === "employee";
  return <div className="admin-shell"><aside className="admin-side"><div className="admin-mark"><ShieldCheck /><div><b>Le Patron Facile</b><span>Administration</span></div></div><nav><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><PackageCheck />Commandes</button>{!employee && <><button className={tab === "products" ? "active" : ""} onClick={() => setTab("products")}><Boxes />Produits</button><button className={tab === "shipping" ? "active" : ""} onClick={() => setTab("shipping")}><MapPinned />Livraisons</button><button className={tab === "messages" ? "active" : ""} onClick={() => setTab("messages")}><Mail />Messages</button><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}><Users />Utilisateurs</button></>}</nav><div className="admin-user"><span>{user.email}</span><small>{role || "profil"}</small><button onClick={() => signOut(auth)}><LogOut /> Déconnexion</button></div></aside><main className="admin-main">{tab === "orders" && <Orders employee={employee}/>} {!employee && tab === "products" && <Products/>} {!employee && tab === "shipping" && <Shipping/>} {!employee && tab === "messages" && <Messages/>} {!employee && tab === "users" && <UsersPage/>}</main></div>;
}

function Login() { const [error, setError] = useState(""), [setup, setSetup] = useState(false); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await signInWithEmailAndPassword(auth, String(f.get("email")), String(f.get("password"))); } catch { setError("Email ou mot de passe incorrect."); } } async function bootstrap(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget), password = String(f.get("password")); try { const credential = await createUserWithEmailAndPassword(auth, "admin@lepatronfacile.dz", password); await setDoc(doc(db, "users", credential.user.uid), { email: "admin@lepatronfacile.dz", role: "admin", active: true, createdAt: serverTimestamp() }); } catch (err: any) { setError(err.code === "auth/email-already-in-use" ? "Ce compte existe déjà : connectez-vous." : "Impossible de créer le compte. Vérifiez qu’Email/Mot de passe et Firestore sont activés."); } } return <div className="admin-login"><form onSubmit={setup ? bootstrap : submit}><ShieldCheck/><p>LE PATRON FACILE</p><h1>{setup ? "Créer le premier admin" : "Administration"}</h1>{setup ? <><p>Compte : <b>admin@lepatronfacile.dz</b></p><label>Mot de passe administrateur<input name="password" type="password" minLength={8} required /></label><small>À conserver précieusement : il ne sera pas envoyé par e-mail.</small></> : <><label>Email<input name="email" type="email" required /></label><label>Mot de passe<input name="password" type="password" required /></label></>}{error && <b>{error}</b>}<button>{setup ? "Créer l’administrateur" : "Se connecter"}</button><button type="button" className="admin-link-button" onClick={() => { setSetup(!setup); setError(""); }}>{setup ? "J’ai déjà un compte" : "Initialiser le premier compte admin"}</button><a href="#/">Retour à la boutique</a></form></div>; }

function SectionHead({ title, count, action }: { title: string; count: number; action?: React.ReactNode }) { return <header className="admin-head"><div><p>BACK-OFFICE</p><h1>{title}</h1><span>{count} éléments</span></div>{action}</header>; }

function Products() { const rows = useRows("products"), [editing, setEditing] = useState<Row | null>(null); async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget), data = { name: f.get("name"), category: f.get("category"), subcategory: f.get("subcategory"), price: Number(f.get("price")), description: f.get("description"), image: f.get("image"), sizes: String(f.get("sizes")).split(",").map(x => x.trim()).filter(Boolean), active: f.get("active") === "on", updatedAt: serverTimestamp() }; if (editing?.id) await updateDoc(doc(db, "products", editing.id), data); else await addDoc(collection(db, "products"), { ...data, createdAt: serverTimestamp() }); setEditing(null); } return <><SectionHead title="Produits" count={rows.length} action={<button className="admin-primary" onClick={() => setEditing({ id: "" })}><Plus/> Ajouter un produit</button>}/><div className="admin-table"><div className="table-row table-title"><span>Produit</span><span>Catégorie</span><span>Prix</span><span>État</span><span/></div>{rows.map(p => <div className="table-row" key={p.id}><span><b>{p.name}</b><small>{p.subcategory}</small></span><span>{p.category}</span><span>{p.price?.toLocaleString("fr-DZ")} DA</span><span><i className={p.active ? "on" : "off"}>{p.active ? "Actif" : "Masqué"}</i></span><span className="actions"><button onClick={() => setEditing(p)}><Pencil/></button><button onClick={() => confirm("Supprimer ce produit ?") && deleteDoc(doc(db, "products", p.id))}><Trash2/></button></span></div>)}</div>{editing && <Modal close={() => setEditing(null)}><form className="admin-form" onSubmit={save}><h2>{editing.id ? "Modifier le produit" : "Nouveau produit"}</h2><label>Nom<input name="name" defaultValue={editing.name} required/></label><div><label>Catégorie<input name="category" defaultValue={editing.category} required/></label><label>Sous-catégorie<input name="subcategory" defaultValue={editing.subcategory}/></label></div><div><label>Prix (DA)<input name="price" type="number" defaultValue={editing.price} required/></label><label>Tailles (séparées par virgule)<input name="sizes" defaultValue={editing.sizes?.join(", ")}/></label></div><label>Image URL<input name="image" defaultValue={editing.image}/></label><label>Description<textarea name="description" defaultValue={editing.description}/></label><label className="check"><input name="active" type="checkbox" defaultChecked={editing.active ?? true}/> Produit actif</label><button className="admin-primary"><Save/> Enregistrer</button></form></Modal>}</>; }

function Orders({ employee }: { employee: boolean }) { const rows = useRows("orders", true), [editing, setEditing] = useState<Row | null>(null); const revenue = useMemo(() => rows.filter(x => x.status !== "Annulée").reduce((a, x) => a + (x.total || 0), 0), [rows]); return <><SectionHead title="Commandes" count={rows.length}/><div className="admin-stats"><div><span>Commandes</span><b>{rows.length}</b></div><div><span>Chiffre d’affaires</span><b>{revenue.toLocaleString("fr-DZ")} DA</b></div><div><span>À traiter</span><b>{rows.filter(x => x.status === "Nouvelle").length}</b></div></div><div className="admin-table orders"><div className="table-row table-title"><span>Client</span><span>Wilaya</span><span>Total</span><span>Statut</span><span/></div>{rows.map(o => <div className="table-row" key={o.id}><span><b>{o.firstName} {o.lastName}</b><small>{o.phone}</small></span><span>{o.wilaya}</span><span>{o.total?.toLocaleString("fr-DZ")} DA</span><span><select value={o.status || "Nouvelle"} onChange={e => updateDoc(doc(db, "orders", o.id), { status: e.target.value, updatedAt: serverTimestamp() })}>{statuses.map(s => <option key={s}>{s}</option>)}</select></span><span className="actions"><button onClick={() => setEditing(o)}><Archive/></button>{!employee && <button onClick={() => confirm("Supprimer cette commande ?") && deleteDoc(doc(db, "orders", o.id))}><Trash2/></button>}</span></div>)}</div>{editing && <Modal close={() => setEditing(null)}><div className="order-detail"><h2>Commande de {editing.firstName} {editing.lastName}</h2><p>{editing.phone} · {editing.wilaya}</p><p>{editing.address}</p>{editing.items?.map((x: any) => <div key={x.name}><span>{x.name} · {x.size} × {x.qty}</span><b>{x.price * x.qty} DA</b></div>)}<strong>Total : {editing.total} DA</strong></div></Modal>}</>; }

function Shipping() { const rows = useRows("shipping"); async function change(id: string, key: string, value: string | boolean) { await updateDoc(doc(db, "shipping", id), { [key]: typeof value === "boolean" ? value : Number(value), updatedAt: serverTimestamp() }); } return <><SectionHead title="Tarifs de livraison" count={rows.length}/><div className="admin-table shipping"><div className="table-row table-title"><span>Wilaya</span><span>Domicile</span><span>Bureau</span><span>Active</span></div>{rows.sort((a,b) => String(a.code).localeCompare(String(b.code))).map(w => <div className="table-row" key={w.id}><span><b>{w.code} · {w.name}</b></span><span><input type="number" defaultValue={w.home} onBlur={e => change(w.id, "home", e.target.value)}/> DA</span><span><input type="number" defaultValue={w.office} onBlur={e => change(w.id, "office", e.target.value)}/> DA</span><span><input type="checkbox" checked={w.active !== false} onChange={e => change(w.id, "active", e.target.checked)}/></span></div>)}</div></>; }

function Messages() { const rows = useRows("messages", true); return <><SectionHead title="Messages" count={rows.length}/><div className="message-grid">{rows.map(m => <article key={m.id}><div><b>{m.name}</b><button onClick={() => deleteDoc(doc(db, "messages", m.id))}><Trash2/></button></div><a href={`tel:${m.phone}`}>{m.phone}</a><p>{m.message}</p><small>{m.createdAt?.toDate?.().toLocaleString("fr-DZ")}</small></article>)}</div></>; }

function UsersPage() { const rows = useRows("users"), [editing, setEditing] = useState(false), [notice, setNotice] = useState(""); async function create(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget), email = String(f.get("email")), password = String(f.get("password")), role = String(f.get("role")); const secondary = initializeApp(firebaseConfig, `user-${Date.now()}`), secondaryAuth = getAuth(secondary); const credential = await createUserWithEmailAndPassword(secondaryAuth, email, password); await setDoc(doc(db, "users", credential.user.uid), { email, role, active: true, createdAt: serverTimestamp() }); await signOut(secondaryAuth); setNotice(`Compte ${email} créé sans confirmation email.`); setEditing(false); } return <><SectionHead title="Utilisateurs" count={rows.length} action={<button className="admin-primary" onClick={() => setEditing(true)}><Plus/> Ajouter</button>}/>{notice && <p className="admin-notice">{notice}</p>}<div className="admin-table users-table"><div className="table-row table-title"><span>Email</span><span>Rôle</span><span>État</span><span/></div>{rows.map(u => <div className="table-row" key={u.id}><span><b>{u.email}</b></span><span>{u.role === "admin" ? "Administrateur" : "Employé"}</span><span><i className={u.active !== false ? "on" : "off"}>{u.active !== false ? "Actif" : "Désactivé"}</i></span><span className="actions"><button onClick={() => updateDoc(doc(db, "users", u.id), { active: u.active === false })}>{u.active === false ? <ShieldCheck/> : <X/>}</button><button onClick={() => confirm("Supprimer ce profil ?") && deleteDoc(doc(db, "users", u.id))}><Trash2/></button></span></div>)}</div>{editing && <Modal close={() => setEditing(false)}><form className="admin-form" onSubmit={create}><h2>Nouvel utilisateur</h2><label>Email<input name="email" type="email" required/></label><label>Mot de passe temporaire<input name="password" type="text" minLength={6} required/></label><label>Rôle<select name="role"><option value="employee">Employé · commandes uniquement</option><option value="admin">Administrateur · accès complet</option></select></label><button className="admin-primary"><Plus/> Créer sans confirmation</button></form></Modal>}</>; }

function Modal({ children, close }: { children: React.ReactNode; close: () => void }) { return <div className="admin-modal"><div className="admin-modal-card"><button className="modal-close" onClick={close}><X/></button>{children}</div></div>; }
